apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-replica-set
  labels:
    app: hello-rs
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello-container
          image: busybox
          command: ['sh', '-c', 'echo Hello from my container! && sleep 3600']